### ISSUE TITLE
[Bug] detached css window popups 

### ISSUE THREAD

**Issue by maxsupermanhd** [BetterDiscord/BetterDiscord#1056]
![image](https://user-images.githubusercontent.com/20772987/134781302-ac76b937-e72f-4b3f-b66f-6efcf3f01cb7.png)

**Comment by dav1312** [comment]
Are you using any plugins?

**Comment by maxsupermanhd** [comment]
> Are you using any plugins?

Yes I am:
```
DoNotTrack
v0.0.7by Zerebos
ImageUtilities
v4.4.8by DevilBro
MyTyping
v1.1by An0
NoReplyMention
v0.0.1by somebody
PlatformIndicators
v0.0.5by Strencher
RemoveBlockedUsers
v1.3.3by DevilBro
```

**Comment by dav1312** [comment]
And have you tested if this also happens without them? Try renaming the plugins folder, restart Discord and see if the issue persists

**Comment by depascalis** [comment]
I temporarily fixed this with this custom ccs, if it is the tooltips you are refering to.
```css
/* Fix for Custom CSS Editor Tooltip */
.appMount-3lHmkl > .layerContainer-yqaFcK {
    z-index: 1002;
}
```
