### ISSUE TITLE
[Bug] BetterDiscord notices are displayed incorrectly in the updated Discord UI

### ISSUE THREAD

**Issue by TheFuzzy** [BetterDiscord/BetterDiscord#1889]
### Before Reporting

- [x] I found no existing issues matching my bug
- [x] My issue is not caused by a plugin or theme

### Describe the Bug

![Image](https://github.com/user-attachments/assets/28e4d796-20bc-43ac-a998-4f63f02bac8e)

After the BD UI update, any notices for Better Discord now display as a tiny box in the bottom left of the window, underneath the user control panel.

I believe this is because the content div has switched to `display: grid` instead of `display: flex`.

### Expected Behavior

![Image](https://github.com/user-attachments/assets/8c406945-4f40-465f-9d64-0a38810216fb)

Notices display at the top, probably under the title.

### Steps To Reproduce

1. Launch Discord with newest version, with the UI refresh update
2. Have updates for plugins available so BD will attempt to display a notice.

### Operating System

Windows

### Discord Version

PTB

### BetterDiscord Version

v1.12.1

### Anything else?

A minimal fix can be done with the following in the BD Custom CSS tab, to place notices in the Discord-designated `notice` grid area:

```css
#bd-notices {
    grid-area: notice;
}
```

**Comment by Riddim-GLiTCH** [comment]
For the time being, I've made this CSS snippet that you could use instead. I'd assume you already have a solution of your own, since you suggested a specific change, but I'll leave this here just in case.


```css
/*fix that update ribbon*/
#bd-notices {
    display: block;
    position: absolute;
    left: 50%;
    top: 30px;
    translate: -50%;
    z-index: 101;
    .bd-notice {
        border-radius: 12px;
        border: 1px solid var(--interactive-active)
    }
}
```

![preview](https://RDG.monarchuploader.de/content/cdn/ROeGwhggIvtW/Discord_lECQzJPcNQ.png)
