### ISSUE TITLE
[Feature] Font size preference for BDD CSS editor

### ISSUE THREAD

**Issue by RheingoldRiver** [BetterDiscord/BetterDiscord#763]
**Is your feature request related to a problem? Please describe.**

The font size in the CSS editor is too small when using nonstandard zoom settings, and every attempt I've made to customize it using custom css has failed (see below).

Here is how small my font size is:

![image](https://user-images.githubusercontent.com/18037011/117522071-ec46d980-af76-11eb-881c-c27944d82b54.png)

Here are my zoom settings:

![image](https://user-images.githubusercontent.com/18037011/117522085-f79a0500-af76-11eb-8bd0-c5786fc43969.png)

And I think in general, people could want to change font size in this editor.

**Describe the feature you'd like**

A preference to set font-size for the CSS editor via some mechanism: ideally, by typing in a number, but a slider from "smallest" to "largest" would also work!

**Additional context**

Here is the css I was trying to use:

```css
.contentColumn-2hrIYH,
#bd-editor-panel,
#bd-customcss-editor {
    max-width:100%!important;
}

#bd-customcss-editor .monaco-editor-hover,
#bd-customcss-editor .lines-content,
#bd-customcss-editor .editor-scrollable,
#bd-customcss-editor .inputarea,
#bd-customcss-editor .view-zones,
#bd-customcss-editor .view-lines,
#bd-customcss-editor .cursors-layer,
#bd-customcss-editor .cursor,
#bd-customcss-editor .view-line {
    font-size: 25px!important;
    line-height:1.1!important;
}

.monaco-editor.no-user-select .view-lines {
    font-size: 22px!important;
}

#bd-customcss-editor { font-size:100%!important;}

#bd-customcss-editor .minimap {
    display:none;
}
```
I asked for help in the BDD support server as well, and 3 different people tried to help me, but none of us could get the highlighting to work. Here is the problem:

![image](https://user-images.githubusercontent.com/18037011/117522062-cb7e8400-af76-11eb-9319-836adcbda061.png)

I'm pretty sure that writing CSS to adjust font size here is extremely nontrivial, and a user preference to set font size would be the preferred way to set font size.

Thanks!
